### ISSUE TITLE
TCRT1000 Inconsistent readings

### ISSUE THREAD

**Issue by zechenturm** [deepjava/runtime-library#18]
When using the TCRT1000 IR sensors within a sufficiently complex  program, a bug in the driver can cause spurious readings that are much lower (i.e. darker) than they should be.
When using these sensors to detect black lines on the ground, that can lead to phantom lines being detected where no actual lines are present.

This is caused by inconsistent timing between triggering a sensor and ADC sampling, namely that the two are split into 2 states of the driver's state machine.
This means that arbitrary code can run in-between triggering the sensor and reading its output, resulting in no guaranteed maximum latency between the 2 events.

In practice, this means the sensors work perfectly with any test/demo program, where not much is happening, and the TCRT1000 task is called in quick succession, but fails to give consistent readings when used in a more complex program, where a single task may take more than 100us to complete:
If such a task runs between between the TCRT1000 trigger and sample states, the IR sensor output is not sampled at its peak, but when the signal is already decaying, causing low readings.
These false readings cause enough fluctuation that they can not be filtered out by only checking differences (discrete derivative) of the readings.
While investigating, the delay between trigger and sample was observed to rise above 150us causing the readings to drop by ~1000 counts.

The quick work around merges the `Start` and `Sample` states into one and uses a `while` loop to wait for 100us.
While this does increase the maximum task execution time to ~100us, it produces reliable sensor readings and is still fast enough to not interfere with the proper scheduling of other tasks.

```
gpio.setValue(trigPin, true);
gpio.setValue(trigPin, false);

while (Kernel.timeUs() - time < 100);
resultVal[sensAdr] = (short) adc.getValue(0);
state = State.Wait;
break;
```

A more permanent fix might include sampling the adc from a timer interrupt, however given how well the current work around behaves, I'm wondering if the extra effort of implementing the timer and the interrupt is actually worth it.
Also a quick check of the sensor output on the oscilloscope suggests we might be able to cut the delay to ~50us, at which point the whole action is probably definitely fast enough to not cause issues for other tasks while also not taking up one of the few Zynq Timers.

**Comment by ursgraf** [comment]
A triple timer is used to generate an interrupt after 100us. The action method is called every ms by the task and shortly afterwards by the irq.
The address lines are switched after each measurement in order to stabilize before the next measurement.
